package: nextcloud
version: '1.6.2'
author: FriendsOfREDAXO
supportpage: hhttps://github.com/FriendsOfREDAXO/nextcloud

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'

page:
    title: NextCloud
    perm: nextcloud[]
    icon: rex-icon fa-cloud
    subpages:
        main:
            title: 'translate:files'
        config:
            title: 'translate:settings'
            perm: admin[]

permissions:
    nextcloud[]: translate:nextcloud_perm_access
    nextcloud[upload_mediapool]: translate:nextcloud_perm_upload_mediapool
    nextcloud[delete]: translate:nextcloud_perm_delete
    nextcloud[download]: translate:nextcloud_perm_download
