package: nextcloud
version: '1.0.0'
author: KLXM
supportpage: https://github.com/klxm/nextcloud

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'

page:
    title: NextCloud
    perm: admin[]
    icon: rex-icon fa-cloud
    subpages:
        main: 
            title: 'translate:files'
        config:
            title: 'translate:settings'
