package: nextcloud
version: '1.0.0'
author: KLXM
supportpage: https://github.com/klxm/nextcloud

requires:
    redaxo: '^5.13.0'
    php:
        version: '>=7.4'

page:
    title: NextCloud
    perm: admin[]
    icon: rex-icon fa-cloud
    subpages:
        main: { title: 'Dateien' }
        config: { title: 'Einstellungen' }